repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-d, "{rules: {document-start: disable}}"]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          ["dbt-duckdb", "sqlfluff-templater-dbt", "deltalake[pyarrow]"]
        args:
          - --dialect
          - duckdb
      - id: sqlfluff-fix
        additional_dependencies:
          ["dbt-duckdb", "sqlfluff-templater-dbt", "deltalake[pyarrow]"]
        args:
          - --dialect
          - duckdb
